name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        TAG_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24' # specify the Go version

      - name: Extract tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build macOS ARM binary
        run: GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o dailysummary-mac-arm-${{ env.TAG_NAME }} dailysummary.go

      - name: Build macOS Intel binary
        run: GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o dailysummary-mac-intel-${{ env.TAG_NAME }} dailysummary.go

      - name: Build Linux Intel binary
        run: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dailysummary-linux-intel-${{ env.TAG_NAME }} dailysummary.go

      - name: Build Windows binary
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dailysummary-windows-${{ env.TAG_NAME }}.exe dailysummary.go

      - name: Create Release and Upload Binaries
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: |
            dailysummary-mac-arm-${{ env.TAG_NAME }}
            dailysummary-mac-intel-${{ env.TAG_NAME }}
            dailysummary-linux-intel-${{ env.TAG_NAME }}
            dailysummary-windows-${{ env.TAG_NAME }}.exe
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
